### ISSUE TITLE
Toon parties

### ISSUE THREAD

**Issue by craigy109** [vincent15k/Toontown-Crystal-Master#17]
On starting a toon party with one of the following games
1. Tug of war
2. cog o war
You press start party the game hangs after you up down the hole to teleport
This also causes the ai server to hang until you restart the district meaning the "temp unavailable sign appears when trying to relog in if server has not been rebooted."

Error that appears in ai

Responding to a get party zone when planning, av,party,zone: 100000009 401099999
 61014
Building 401002994 (3300): cogdoTakeOver
party requested: host 100000009, start 2015-07-24 09:50:00, end 2015-07-24 10:20
:00, private 0, invitetheme 1, activities omitted, decor omitted, invitees []
responding to client now that ud got back to us
querying for details against hostId 100000009
Assertion failed: Distributed class DistributedPartyTugOfWarActivity doesn't hav
e getter named getPlayersPerTeam to match required field setPlayersPerTeam at li
ne 827 of c:\users\toontowninfinite\desktop\github\panda3d\direct\src\dcparser\d
cClass.cxx
Traceback (most recent call last):
  File "C:\Users\Craigy\Desktop\Toontown-Crystal-Master-master\src\dependencies\
panda\python\direct\distributed\ConnectionRepository.py", line 613, in readerPol
lUntilEmpty
    while self.readerPollOnce():
  File "C:\Users\Craigy\Desktop\Toontown-Crystal-Master-master\src\dependencies\
panda\python\direct\distributed\ConnectionRepository.py", line 618, in readerPol
lOnce
    if self.checkDatagram():
  File "toontown\uberdog\DistributedPartyManagerAI.py", line 158, in partyInfoOf
HostResponseUdToAi
    partyAI.generateWithRequiredAndId(self.air.allocateChannel(), self.air.distr
ictId, zoneId)
  File "C:\Users\Craigy\Desktop\Toontown-Crystal-Master-master\src\dependencies\
panda\python\direct\distributed\DistributedObjectAI.py", line 393, in generateWi
thRequiredAndId
    self.generate()
  File "toontown\parties\DistributedPartyAI.py", line 77, in generate
    act.generateWithRequired(self.zoneId)
  File "C:\Users\Craigy\Desktop\Toontown-Crystal-Master-master\src\dependencies\
panda\python\direct\distributed\DistributedObjectAI.py", line 377, in generateWi
thRequired
    self.air.generateWithRequired(self, parentId, zoneId, optionalFields)
  File "C:\Users\Craigy\Desktop\Toontown-Crystal-Master-master\src\dependencies\
panda\python\direct\distributed\AstronInternalRepository.py", line 417, in gener
ateWithRequired
    self.generateWithRequiredAndId(do, doId, parentId, zoneId, optionalFields)
  File "C:\Users\Craigy\Desktop\Toontown-Crystal-Master-master\src\dependencies\
panda\python\direct\distributed\AstronInternalRepository.py", line 428, in gener
ateWithRequiredAndId
    do.sendGenerateWithRequired(self, parentId, zoneId, optionalFields)
  File "C:\Users\Craigy\Desktop\Toontown-Crystal-Master-master\src\dependencies\
panda\python\direct\distributed\DistributedObjectAI.py", line 447, in sendGenera
teWithRequired
    optionalFields)
AssertionError: Distributed class DistributedPartyTugOfWarActivity doesn't have
getter named getPlayersPerTeam to match required field setPlayersPerTeam at line
 827 of c:\users\toontowninfinite\desktop\github\panda3d\direct\src\dcparser\dcC
lass.cxx
:task(error): Exception occurred in PythonTask readerPollTask-35755160
Traceback (most recent call last):
  File "C:\Users\Craigy\Desktop\Toontown-Crystal-Master-master\src\dependencies\
panda\python\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Users\Craigy\Desktop\Toontown-Crystal-Master-master\src\dependencies\
panda\python\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Users\Craigy\Desktop\Toontown-Crystal-Master-master\src\toontown\ai\S
erviceStart.py", line 64, in <module>
    run()
  File "otp\ai\AIBase.py", line 167, in run
    self.taskMgr.run()
  File "C:\Users\Craigy\Desktop\Toontown-Crystal-Master-master\src\dependencies\
panda\python\direct\task\Task.py", line 502, in run
    self.step()
  File "C:\Users\Craigy\Desktop\Toontown-Crystal-Master-master\src\dependencies\
panda\python\direct\task\Task.py", line 460, in step
    self.mgr.poll()
  File "C:\Users\Craigy\Desktop\Toontown-Crystal-Master-master\src\dependencies\
panda\python\direct\distributed\ConnectionRepository.py", line 613, in readerPol
lUntilEmpty
    while self.readerPollOnce():
  File "C:\Users\Craigy\Desktop\Toontown-Crystal-Master-master\src\dependencies\
panda\python\direct\distributed\ConnectionRepository.py", line 618, in readerPol
lOnce
    if self.checkDatagram():
  File "toontown\uberdog\DistributedPartyManagerAI.py", line 158, in partyInfoOf
HostResponseUdToAi
    partyAI.generateWithRequiredAndId(self.air.allocateChannel(), self.air.distr
ictId, zoneId)
  File "C:\Users\Craigy\Desktop\Toontown-Crystal-Master-master\src\dependencies\
panda\python\direct\distributed\DistributedObjectAI.py", line 393, in generateWi
thRequiredAndId
    self.generate()
  File "toontown\parties\DistributedPartyAI.py", line 77, in generate
    act.generateWithRequired(self.zoneId)
  File "C:\Users\Craigy\Desktop\Toontown-Crystal-Master-master\src\dependencies\
panda\python\direct\distributed\DistributedObjectAI.py", line 377, in generateWi
thRequired
    self.air.generateWithRequired(self, parentId, zoneId, optionalFields)
  File "C:\Users\Craigy\Desktop\Toontown-Crystal-Master-master\src\dependencies\
panda\python\direct\distributed\AstronInternalRepository.py", line 417, in gener
ateWithRequired
    self.generateWithRequiredAndId(do, doId, parentId, zoneId, optionalFields)
  File "C:\Users\Craigy\Desktop\Toontown-Crystal-Master-master\src\dependencies\
panda\python\direct\distributed\AstronInternalRepository.py", line 428, in gener
ateWithRequiredAndId
    do.sendGenerateWithRequired(self, parentId, zoneId, optionalFields)
  File "C:\Users\Craigy\Desktop\Toontown-Crystal-Master-master\src\dependencies\
panda\python\direct\distributed\DistributedObjectAI.py", line 447, in sendGenera
teWithRequired
    optionalFields)
AssertionError: Distributed class DistributedPartyTugOfWarActivity doesn't have
getter named getPlayersPerTeam to match required field setPlayersPerTeam at line
 827 of c:\users\toontowninfinite\desktop\github\panda3d\direct\src\dcparser\dcC
lass.cxx

**Comment by craigy109** [comment]
Also at toon parties once the firework show has been activated the clouds in the sky despawn as they should but do not respawn once the fireworks show is over making the cannon game de-active for the rest of the party.

**Comment by craigy109** [comment]
When you fire out of a cannon and it tells you how many beans you have won you can move around with the popup screen on and go onto other games , then press okay and use stuff like the trampoline while moving and cheat

**Comment by vincent15k** [comment]
Does it break when you only choose **those two games**?

**Comment by craigy109** [comment]
@vincent15k yes its only with these two games its something do do with detecting how many players on each team. all the other games i have tested one by one and work great. other than the bugs i posted in my other comments

**Comment by DenialMC** [comment]
(facepalm)
